name: delete_images_replacewithimagepath
on: workflow_dispatch
permissions:
  contents: write

jobs:
  deleteimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: delete
        run: rm -r replacewithimagepath
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config pull.rebase false
          git add -A
          git commit -m "delete replacewithimagepath" -a || echo "No changes to commit"
      - name: pull
        run: git pull origin main
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 